// KartWheel Types
export const SET_PAYMENT_TYPE = 'SET_PAYMENT_TYPE';
export const SET_TICKET_TIERS = 'SET_TICKET_TIERS';
export const SET_CURRENT_TICKET_TIER = 'SET_CURRENT_TICKET_TIER';
export const REQUEST_EVENT_INFO = 'REQUEST_EVENT_INFO';
export const RECEIVE_EVENT_INFO = 'RECEIVE_EVENT_INFO';
export const REQUEST_DISCOUNT_INFO = 'REQUEST_DISCOUNT_INFO';
export const RECEIVE_DISCOUNT_INFO = 'RECEIVE_DISCOUNT_INFO';
export const REQUEST_PAYMENT_CREATION = 'REQUEST_PAYMENT_CREATION';
export const RECEIVE_PAYMENT_CREATION = 'RECEIVE_PAYMENT_CREATION';
